/**
 * Elenco fijo de parodias obvias de íconos del boxeo, agrupadas por nacionalidad.
 * Son personajes INVENTADOS con nombres-chiste: no representan a personas reales
 * ni usan su imagen. El campo `referencia` existe solo para que se entienda el guiño.
 *
 * Cada país tiene sus máximas leyendas (rol 'leyenda', retiradas, récords a superar)
 * y al menos un peleador en actividad (rol 'activo', rival posible del jugador).
 */
export const PARODIAS = [
  // 🇺🇸 Estados Unidos
  { id: 'tyzon', nombre: 'Dyke Tyzon', apodo: 'El Ciclón', referencia: 'Mike Tyson', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'agresivo', rol: 'activo', media: 82, edad: 26, frase: 'Todos tienen un plan hasta que les apago la luz.' },
  { id: 'alla', nombre: 'Muhammad Allá', apodo: 'El Más Grande', referencia: 'Muhammad Ali', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'showman', rol: 'leyenda', media: 90, edad: 52, frase: 'Floto como mariposa y cobro como abeja reina.' },
  { id: 'mayweder', nombre: 'Floyd Mayweder', apodo: 'El Intocable', referencia: 'Floyd Mayweather', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'provocador', rol: 'leyenda', media: 88, edad: 49, frase: 'Cero derrotas. Contá de nuevo: cero.' },
  { id: 'robinson', nombre: 'Shugar Ray Robinsón', apodo: 'Azúcar', referencia: 'Sugar Ray Robinson', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'mentor', rol: 'leyenda', media: 91, edad: 61, frase: 'Antes de vos, el estilo lo inventé yo.' },
  // v7 ("agregá más parodias, muy obvias, si es posible"):
  { id: 'foreman', nombre: 'Jorge Foremán', apodo: 'Grandote de Houston', referencia: 'George Foreman', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'mentor', rol: 'leyenda', media: 90, edad: 63, frase: 'Pegué una vez. Con esa alcanzó siempre.' },
  { id: 'frasier', nombre: 'Joe Frasier', apodo: 'El Fumador', referencia: 'Joe Frazier', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'presionador', personalidad: 'agresivo', rol: 'leyenda', media: 89, edad: 58, frase: 'Para adelante toda la pelea. Para atrás, nunca.' },
  { id: 'holifil', nombre: 'Evander Holifil', apodo: 'Campo Santo', referencia: 'Evander Holyfield', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'respetuoso', rol: 'leyenda', media: 88, edad: 60, frase: 'Me arrancaron un pedazo de oreja y seguí firme. Eso lo dice todo.' },
  { id: 'delahoyo', nombre: 'Oscar De La Hoyo', apodo: 'El Chico de Oro', referencia: 'Oscar De La Hoya', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'showman', rol: 'leyenda', media: 87, edad: 51, frase: 'Vendí más entradas que nadie. Y encima ganaba.' },
  { id: 'jagler', nombre: 'Marvin Jaglér', apodo: 'Maravilloso', referencia: 'Marvin Hagler', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'mediano', estilo: 'presionador', personalidad: 'agresivo', rol: 'leyenda', media: 90, edad: 63, frase: 'Pelado, zurdo y sin miedo. Así se hace historia.' },
  { id: 'janey', nombre: 'Devin Jáney', apodo: 'El Ordenado', referencia: 'Devin Haney', nacionalidad: 'US', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'mercenario', rol: 'activo', media: 83, edad: 25, frase: 'Gano rounds como quien llena una planilla.' },

  // 🇲🇽 México
  { id: 'chaves', nombre: 'Julio César Cháves', apodo: 'El César', referencia: 'Julio César Chávez', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'menton', personalidad: 'agresivo', rol: 'leyenda', media: 89, edad: 54, frase: 'Ochenta y siete peleas sin perder. Buscá el dato.' },
  { id: 'canolo', nombre: 'Canolo Álvarez', apodo: 'El Pelirrojo', referencia: 'Canelo Álvarez', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'mercenario', rol: 'activo', media: 84, edad: 30, frase: 'Si la bolsa es buena, subo con cualquiera.' },
  { id: 'oliveros', nombre: 'Rubén Oliveros', apodo: 'Las Púas', referencia: 'Rubén "Púas" Olivares', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'noqueador', personalidad: 'showman', rol: 'leyenda', media: 86, edad: 57, frase: 'Fiesta toda la noche y nocaut a la tarde.' },
  // v7:
  { id: 'santez', nombre: 'Zalvador Sántez', apodo: 'El Cerebro de Cuernavaca', referencia: 'Salvador Sánchez', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'mentor', rol: 'leyenda', media: 90, edad: 60, frase: 'Pensaba dos rounds antes de que pasaran.' },
  { id: 'marques', nombre: 'Juan Manuel Marqués', apodo: 'El Contraataque', referencia: 'Juan Manuel Márquez', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'contragolpeador', personalidad: 'respetuoso', rol: 'leyenda', media: 88, edad: 51, frase: 'Esperá el error del otro. Siempre llega.' },
  { id: 'moralez', nombre: 'Erik Moralez', apodo: 'El Terrible', referencia: 'Erik Morales', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'presionador', personalidad: 'agresivo', rol: 'leyenda', media: 87, edad: 48, frase: 'Cuatro categorías, un solo estilo: para adelante.' },
  { id: 'barreira', nombre: 'Marco Antonio Barreira', apodo: 'La Guerra', referencia: 'Marco Antonio Barrera', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'agresivo', rol: 'leyenda', media: 87, edad: 50, frase: 'Cada pelea mía fue una guerra. Preguntale a mis rivales.' },
  { id: 'munguilla', nombre: 'Jaime Munguilla', apodo: 'El Rayo de Tijuana', referencia: 'Jaime Munguía', nacionalidad: 'MX', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'agresivo', rol: 'activo', media: 82, edad: 27, frase: 'Vengo de la frontera y no aflojo nunca.' },

  // 🇦🇷 Argentina
  { id: 'monzonte', nombre: 'Carlos Monzonte', apodo: 'El Escopeta', referencia: 'Carlos Monzón', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'agresivo', rol: 'leyenda', media: 89, edad: 55, frase: 'Acá se viene a aguantar. El que aguanta, gana.' },
  { id: 'maravia', nombre: 'Sergio "Maravía" Martino', apodo: 'Maravía', referencia: 'Sergio "Maravilla" Martínez', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'respetuoso', rol: 'activo', media: 81, edad: 32, frase: 'Las manos abajo y la cabeza en otro lado. Probá pegarme.' },
  { id: 'lecho', nombre: 'Nicolino Lecho', apodo: 'El Intocable de Mendoza', referencia: 'Nicolino Locche', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'showman', rol: 'leyenda', media: 87, edad: 58, frase: 'Yo no esquivo golpes: los invito a pasar de largo.' },
  // v7:
  { id: 'peres', nombre: 'Pascual Peres', apodo: 'El Match Boy', referencia: 'Pascual Pérez', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'respetuoso', rol: 'leyenda', media: 86, edad: 65, frase: 'Chiquito de cuerpo, gigante de récord.' },
  { id: 'galindes', nombre: 'Víctor Galindes', apodo: 'El Látigo', referencia: 'Víctor Galíndez', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'mediano', estilo: 'presionador', personalidad: 'mentor', rol: 'leyenda', media: 88, edad: 62, frase: 'Diez defensas seguidas. Contalas de nuevo.' },
  { id: 'acavayo', nombre: 'Horacio Acavayo', apodo: 'El Zurdo de Saavedra', referencia: 'Horacio Accavallo', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'pluma', estilo: 'zurdo_cruzado', personalidad: 'mentor', rol: 'leyenda', media: 85, edad: 66, frase: 'Me retiré invicto porque supe cuándo parar.' },
  { id: 'gatica', nombre: 'José María Gátika', apodo: 'El Mono', referencia: 'José María Gatica', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'pluma', estilo: 'noqueador', personalidad: 'showman', rol: 'leyenda', media: 84, edad: 60, frase: 'Mono, pero con las manos de oro.' },
  { id: 'martilez', nombre: 'Fernando Martilez', apodo: 'El Aguante de Quilmes', referencia: 'Fernando Martínez', nacionalidad: 'AR', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'mercenario', rol: 'activo', media: 81, edad: 29, frase: 'Me pueden pegar todo el día. No me voy a caer.' },

  // 🇪🇸 España
  { id: 'legran', nombre: 'José Legrán', apodo: 'El Puma de Baracoa', referencia: 'José Legrá', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'showman', rol: 'leyenda', media: 85, edad: 56, frase: 'Bailo, pego y me voy sin despeinarme.' },
  { id: 'perico', nombre: 'Perico Fernándes', apodo: 'El Chaval', referencia: 'Perico Fernández', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'pluma', estilo: 'noqueador', personalidad: 'provocador', rol: 'leyenda', media: 83, edad: 53, frase: 'De la calle al título. Sin escalas.' },
  { id: 'diez', nombre: 'Poli Díez', apodo: 'El Potro de Vallecas', referencia: 'Poli Díaz', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'pluma', estilo: 'menton', personalidad: 'tramposo', rol: 'activo', media: 78, edad: 28, frase: 'Yo peleo como vivo: sin frenos.' },
  // v7:
  { id: 'urtain', nombre: 'José Manuel Urtaine', apodo: 'El Vasco Atómico', referencia: 'José Manuel Ibar "Urtain"', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'showman', rol: 'leyenda', media: 85, edad: 70, frase: 'Pegaba tan fuerte que hasta yo me asustaba.' },
  { id: 'castilleja', nombre: 'Javier Castilleja', apodo: 'El Lince de Parla', referencia: 'Javier Castillejo', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'respetuoso', rol: 'leyenda', media: 84, edad: 55, frase: 'Técnica, paciencia y un buen rincón. Con eso alcanza.' },
  { id: 'uskudun', nombre: 'Paulino Uskudún', apodo: 'El Roble de Régil', referencia: 'Paulino Uzcudun', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'mentor', rol: 'leyenda', media: 83, edad: 72, frase: 'Nadie me tumbó nunca. Lo intentaron todos.' },
  { id: 'legarraga', nombre: 'Kerman Legárraga', apodo: 'El Puño de Bilbao', referencia: 'Kerman Lejarraga', nacionalidad: 'ES', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'agresivo', rol: 'activo', media: 80, edad: 30, frase: 'Cada pelea mía dura poco. Mejor para todos.' },

  // 🇮🇹 Italia
  { id: 'benvenuto', nombre: 'Nino Benvenuto', apodo: 'El Elegante', referencia: 'Nino Benvenuti', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'mediano', estilo: 'tecnico', personalidad: 'respetuoso', rol: 'leyenda', media: 87, edad: 57, frase: 'El boxeo es una conversación. Yo hablo más claro.' },
  { id: 'marchiano', nombre: 'Rocky Marchiano', apodo: 'El Martillo', referencia: 'Rocky Marciano', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'mentor', rol: 'leyenda', media: 90, edad: 60, frase: 'Me retiré invicto. Vos fijate qué hacés con tu vida.' },
  { id: 'carnero', nombre: 'Primo Carnero', apodo: 'La Montaña', referencia: 'Primo Carnera', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'mercenario', rol: 'activo', media: 79, edad: 29, frase: 'Soy grande, lento y te voy a alcanzar igual.' },
  // v7:
  { id: 'loy', nombre: 'Duilio Loy', apodo: 'El Genovés', referencia: 'Duilio Loi', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'respetuoso', rol: 'leyenda', media: 86, edad: 68, frase: 'Nunca perdí el cinturón arriba del ring.' },
  { id: 'antuofermo', nombre: 'Vito Antuofermó', apodo: 'El Toro de Bari', referencia: 'Vito Antuofermo', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'mediano', estilo: 'presionador', personalidad: 'agresivo', rol: 'leyenda', media: 85, edad: 58, frase: 'Vengo, empujo y no freno hasta la campana.' },
  { id: 'olivo', nombre: 'Patrizio Olivo', apodo: 'El Elegante de Nápoles', referencia: 'Patrizio Oliva', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'showman', rol: 'leyenda', media: 84, edad: 60, frase: 'El boxeo también puede ser lindo. Yo lo demostré.' },
  { id: 'vianelo', nombre: 'Guido Vianelo', apodo: 'El Gigante Romano', referencia: 'Guido Vianello', nacionalidad: 'IT', disciplina: 'boxeo', categoria: 'mediano', estilo: 'noqueador', personalidad: 'mercenario', rol: 'activo', media: 79, edad: 31, frase: 'Grande como Roma y con la misma paciencia: cero.' },

  // 🇯🇵 Japón
  { id: 'inue', nombre: 'Naoya Inue', apodo: 'El Monstruo', referencia: 'Naoya Inoue', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'pluma', estilo: 'noqueador', personalidad: 'respetuoso', rol: 'activo', media: 85, edad: 27, frase: 'No hablo mucho. Los rounds tampoco duran mucho.' },
  { id: 'harata', nombre: 'Fighting Harata', apodo: 'El Puño del Sol', referencia: 'Fighting Harada', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'pluma', estilo: 'menton', personalidad: 'agresivo', rol: 'leyenda', media: 86, edad: 59, frase: 'Presión desde la campana hasta la campana.' },
  { id: 'sendo', nombre: 'Takeshi Sendo', apodo: 'El Jabalí de Naniwa', referencia: 'Takeshi Sendo', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'mediano', estilo: 'menton', personalidad: 'provocador', rol: 'activo', media: 80, edad: 28, frase: 'Vení para acá que esto recién empieza.' },
  // v7:
  { id: 'wayima', nombre: 'Koichi Wayima', apodo: 'El Zurdo Imperial', referencia: 'Kōichi Wajima', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'mediano', estilo: 'zurdo_cruzado', personalidad: 'mentor', rol: 'leyenda', media: 87, edad: 78, frase: 'Fui el primer campeón japonés en subir tan alto. No el último.' },
  { id: 'ishimatsu', nombre: 'Guts Ishimatsú', apodo: 'Las Agallas', referencia: 'Guts Ishimatsu', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'pluma', estilo: 'presionador', personalidad: 'agresivo', rol: 'leyenda', media: 85, edad: 74, frase: 'El nombre no es casualidad: agallas es lo único que necesité.' },
  { id: 'ioca', nombre: 'Kazuto Ioca', apodo: 'El Relojero de Osaka', referencia: 'Kazuto Ioka', nacionalidad: 'JP', disciplina: 'boxeo', categoria: 'pluma', estilo: 'tecnico', personalidad: 'provocador', rol: 'activo', media: 81, edad: 26, frase: 'Cambio de categoría como quien cambia de reloj.' },
];
